[project]
name = "project-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sanchali-rif", email = "sanchalisaha05@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain-google-genai>=4.3.3",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.2.2",
    "streamlit>=1.61.1",
]

[project.scripts]
project-2 = "project_2:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
